version: '3'

services:

  #  start Postgres, and ensure that data is stored to a mounted volume
  postgres:
    image: 'caddy:2.4.6-alpine'
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./dist:/dist
      - ./Caddyfile:/etc/caddy/Caddyfile

